# Generated by Django 5.2.16 on 2026-08-09 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_destination_blogpost_experience_and_more'),
        ('properties', '0002_destination_alter_wishlist_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('EAT', 'Eat Here'), ('RITUAL', 'Morning Rituals'), ('QUIET', 'Quiet Places'), ('CRAFT', 'Local Craft'), ('WALK', 'Walk Here'), ('CULTURE', 'Local Culture'), ('SUNSET', 'Watch the Sunset'), ('FAMILY', 'Family Favorites'), ('HISTORY', 'Local History'), ('SMALL_BIZ', 'Small Businesses')], default='EAT', max_length=50)),
                ('description', models.TextField()),
                ('location_name', models.CharField(help_text='e.g. Dadar West Market, Shivaji Park', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='secrets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Consent to publish this story')),
                ('consent_visibility', models.CharField(choices=[('PUBLIC', 'Public (Anyone can see)'), ('COMMUNITY', 'Community (Logged-in users)'), ('PRIVATE', 'Private (Review required)')], default='PUBLIC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voices/')),
                ('transcript', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('intro', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('home_description', models.TextField(blank=True)),
                ('home_history', models.TextField(blank=True)),
                ('home_architecture', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='families/')),
                ('home_photo', models.ImageField(blank=True, null=True, upload_to='families/')),
                ('host_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('ingredients', models.TextField()),
                ('preparation_steps', models.TextField()),
                ('family_memory', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='properties.experience')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='core.family')),
            ],
        ),
        migrations.CreateModel(
            name='SecretRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('why_love', models.TextField()),
                ('what_to_try', models.TextField(blank=True)),
                ('when_to_go', models.CharField(blank=True, max_length=150)),
                ('local_etiquette', models.TextField(blank=True, help_text='Tips on how to behave respectfully')),
                ('price_range', models.CharField(blank=True, help_text='e.g. Budget, Moderate, Splurge', max_length=50)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('COMMUNITY', 'Community (Logged-in Only)'), ('GUESTS', 'LocalNest Guests (Booked Guests)'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.localsecret')),
                ('recommended_by_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_recommendations', to='core.family')),
                ('recommended_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='traditions/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traditions', to='core.family')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('FAMILY', 'Family Stories'), ('FOOD', 'Food Stories'), ('CRAFT', 'Craft Stories'), ('VILLAGE', 'Village Stories'), ('HERITAGE', 'Heritage Stories'), ('WOMEN', 'Women-led Stories'), ('GENERATIONAL', 'Generational Stories'), ('ARTISAN', 'Artisan Stories'), ('FARMER', 'Farmer Stories'), ('HOME', 'Home Stories')], default='FAMILY', max_length=50)),
                ('intro', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('moderation_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('COMMUNITY', 'Community (Logged-in Only)'), ('GUESTS', 'LocalNest Guests (Booked Guests)'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_stories', to='properties.destination')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_stories', to='properties.experience')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.family')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_stories', to='properties.property')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.recipe')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.storycontributor')),
                ('tradition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.tradition')),
                ('voice_recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.voicerecording')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
