# Generated by Django 5.2.16 on 2026-08-17 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hostprofile_achievements_and_more'),
        ('bookings', '0002_booking_experiences_passportbadge'),
        ('core', '0003_localsecret_storycontributor_voicerecording_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='memories/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='bookings.booking')),
                ('saved_recipes', models.ManyToManyField(blank=True, related_name='saved_memories', to='core.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
