# Generated by Django 5.2.16 on 2026-07-25 08:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text="Bootstrap Icon class, e.g., 'bi-wifi' or 'bi-snow'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, max_length=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('private_room', models.BooleanField(default=True, help_text='True if guests get a private room; False if shared living space')),
                ('house_rules', models.TextField(blank=True)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('languages_spoken', models.CharField(help_text='Comma-separated languages spoken by host family (e.g., English, Hindi)', max_length=255)),
                ('nearby_attractions', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breakfast_included', models.BooleanField(default=False)),
                ('breakfast_details', models.CharField(blank=True, max_length=255)),
                ('lunch_included', models.BooleanField(default=False)),
                ('lunch_details', models.CharField(blank=True, max_length=255)),
                ('dinner_included', models.BooleanField(default=False)),
                ('dinner_details', models.CharField(blank=True, max_length=255)),
                ('vegetarian', models.BooleanField(default=True)),
                ('non_vegetarian', models.BooleanField(default=False)),
                ('custom_notes', models.TextField(blank=True, max_length=1000)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_menu', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
