# Generated by Django 5.2.16 on 2026-07-26 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('description', models.TextField()),
                ('best_season', models.CharField(blank=True, max_length=150)),
                ('local_food', models.CharField(blank=True, max_length=255)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='cooking_style',
            field=models.CharField(default='Traditional wood-fired', max_length=100),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='food_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='food_menus/'),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='food_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='food_menus/'),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='jain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='local_desserts',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='special_dishes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='spice_level',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='weekly_menu',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.destination'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_wishlists', to='properties.destination'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiences/')),
                ('category', models.CharField(default='Village Walk', max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_wishlists', to='properties.experience'),
        ),
    ]
