# Generated by Django 5.2.16 on 2026-08-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_destination_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['image']},
        ),
    ]
