# Generated by Django 5.2.16 on 2026-07-26 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0002_destination_alter_wishlist_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='properties.experience'),
        ),
        migrations.CreateModel(
            name='PassportBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('DESTINATION', 'Destination'), ('CULTURE', 'Culture'), ('FOOD', 'Food'), ('EXPERIENCE', 'Experience')], default='DESTINATION', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(default='bi-award', max_length=50)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_badges', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
